### ISSUE TITLE
Loading large dataset through jsreport.renderAsync returns error

### ISSUE THREAD

**Issue by staterium** [jsreport/jsreport-browser-client-dist#10]
**Server:** 
jsreport running in Docker on Azure (jsreport/jsreport latest from Docker Hub)

**Client:**
Vue app using jsreport browser-client 

**Process:**
Client calls own API to retrieve report data, and uses browser-client to render report. Report is displayed in new window with iframe and res.toObjectURL();

**Config:**
jsreport.serverUrl = "https://foobar.azurewebsites.net";
var auth = "Basic " + btoa("admin:mypassword");
jsreport.headers["Authorization"] = auth;

**Request object:** 
{
	"url": "https://foobar.azurewebsites.net/api/report",
	"template": {
		"name": "MyReport",
		"engine": "handlebars",
		"recipe": "chrome-pdf"
	},
	"data":  myData
}
where myData is a json object measuring around 800kb in size.

jsreport.renderAsync(request) fails and _then_ promise never kept. Error in _catch_ promise is as follows:
{
"status": 500,
"error": "Navigation failed because browser has disconnected!",
stack: "Error: Navigation failed because browser has disconnected!
    at CDPSession.<anonymous> (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:46:107)
    at CDPSession.emit (events.js:200:13)
    at CDPSession._onClosed (/app/node_modules/puppeteer/lib/Connection.js:215:10)
    at Connection._onClose (/app/node_modules/puppeteer/lib/Connection.js:138:15)
    at WebSocket.<anonymous> (/app/node_modules/puppeteer/lib/WebSocketTransport.js:45:22)
    at WebSocket.onClose (/app/node_modules/puppeteer/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:200:13)
    at WebSocket.emitClose (/app/node_modules/puppeteer/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/app/node_modules/puppeteer/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:200:13)
    at TCP.<anonymous> (net.js:586:12)
  -- ASYNC --
    at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/app/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:23)
    at /app/node_modules/jsreport-chrome-pdf/lib/conversion.js:43:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async /app/node_modules/jsreport-chrome-pdf/lib/conversion.js:200:22"
}

Note that everything works fine for smaller data sets.

**Comment by staterium** [comment]
Update:

I'm seeing the same issue when loading a large data set directly into jsreport studio as sample data:

[https://imgur.com/a/afqeDWF](https://imgur.com/a/afqeDWF)

This leads me to believe this is not a browser-client issue?

**Comment by bjrmatos** [comment]
hi!

> This leads me to believe this is not a browser-client issue?

it can be the case.. how much large is the data? if you have some way to share the template and data i can give it a try in my local and check if we can do something to make chrome not break on your case.

**Comment by staterium** [comment]
Template and sample data here:

https://drive.google.com/open?id=1gt_y99qrJIl_NRV52yvJOYTubXXNbGtz

**Comment by bjrmatos** [comment]
hi! i'm using the same template and data and i can't reproduce the problem, the pdf is produced normally in the studio. i'm using the same image on docker `jsreport/jsreport`, are you sure that the file on google drive it is the same data in your test case?

<img width="1470" alt="Captura de pantalla 2019-06-17 a las 2 08 00 p m" src="https://user-images.githubusercontent.com/4262050/59630026-e1c49200-9109-11e9-80a8-22666d8d59e9.png">

produced PDF:

[sample-template.pdf](https://github.com/jsreport/jsreport-browser-client-dist/files/3298473/sample-template.pdf)

**Comment by staterium** [comment]
Hi,

Yes, I copied the template and data straight from my instance of jsreport studio.

The only difference must then be that my studio is hosted in Azure? Is it that there are limits in Azure of what puppeteer can do?

**Comment by bjrmatos** [comment]
i will try to run it on azure and let you know (probably tomorrow).

NOTES: for reference this is the entities zip for the test case

[export-template-crash.zip](https://github.com/jsreport/jsreport-browser-client-dist/files/3298662/export-template-crash.zip)

**Comment by pofider** [comment]
I tried running this on azure web app. 
And it is crashing as described even on 7GB memory instance.
I found out it is crashing because of the image logo.
I resized the image to the size you actually need - 200px.
Then it was working fine even on the free instance.

I am not sure what is wrong with the image, because if I put there a different image which is 3x bigger, it works fine. Probably some secret problem in azure/chrome we won't find out. 
So just resize your image and you should be fine.

Note that it is typically the best approach to remove stuff from your template and step by step find out what is causing performance issues or chrome crash.

**Comment by SfApi** [comment]
Hi, 

I did that test before I opened the issue as I suspected it was the image:

https://imgur.com/L0zlLtk

As you can see without the image the problem persists.

**Comment by staterium** [comment]
Hi,

I did that test before I opened the issue as I suspected it was the image:

https://imgur.com/L0zlLtk

As you can see without the image the problem persists.

**Comment by staterium** [comment]
(unless that is a different error)

**Comment by pofider** [comment]
It could have happened that azure got somehow corrupted with the original image and thus removing it didn't have an effect. Try to restart the web app in such cases. You should wait until your templates are deleted to be sure it was restarted.

Anyway... My full exact specification. Please try to follow exactly the same:

1. - web app linux / docker image / west europe
2. - premium v2 P1v2
3. - single container, dockerhub, jsreport/jsreport docker image
4. - create
5. - open studio, you should see version 2.5.0 in the browser tab title
6. - import this using studio settings
[export (45).zip](https://github.com/jsreport/jsreport-browser-client-dist/files/3307580/export.45.zip)
I use an asset for pasting the image but it should, in the end, send the same base64 to chrome.
7. - the template should work

I have no clue what can be wrong for this image or why is azure/chrome behaving like that. It can be some kind of azure web app specific thing. It is a big black box and you can always run a normal VM and host the jsreport there. There shouldn't be such problems. Or at least nothing of that kind was reported.
