### ISSUE TITLE
URIError when call renderAsync res.toString()

### ISSUE THREAD

**Issue by aleksandar78** [jsreport/jsreport-browser-client-dist#11]
Hi,

I'm using JS Report 'jsreport-browser-client-dist' with ReactJS app. 

Dependencies:
jsreport-browser-client-dist: 1.3.0
react: 16.8.6

I've found some examples, not many to be honest, how to call jsreport server from a browser and render PDF. I'm trying to render the report in HTML format. 
Currently, I'm googling and reading source code to catch what methods to call, etc. 

The main problem is that I have URLError with this code:
```js
try {
      const json = await api.getDetails(+id);
      console.log(json);
      setDetails(json);

      jsreport.serverUrl = 'http://devsrv:5488';
      jsreport.headers = {
        Authorization: 'Basic YWRtaW46YWRtaW4=',
      };
      const reportRequest = { template: { shortid: 'aofjeifaofja' }, data: json };
      jsreport.renderAsync(reportRequest).then((res: any) => {
        const htmlResponse = res.toString(); // error is thrown here
        const extractedScript = /<script>[\s\S]*<\/script>/g.exec(htmlResponse);
        console.log('html is: ', htmlResponse);
        console.log('script is: ', extractedScript);
        setHtmlInvoice(htmlResponse);
      });
    } catch (e) {
      console.log(e);
    }
```

**URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at ArrayBuffer.response.toString (jsreport.js:353)**

I've tried to call all other methods on response object:
* res.toBlob()
* res.toDataURI()
* res.toObjectURL()

and everything works fine. 

Unfortunately for me, I need to include HTML and not PDF, etc. 

Any tip or feedback is welcome 

Thanks

**Comment by bjrmatos** [comment]
hi! sorry for the late response.. hmm i would like to reproduce the sample on my own, can you create an export zip with the template and everything you need to run the template?, also i will need that you share the value of the json you get from your server (api.getDetails call). if the res.toDataURI call works for you then i would like to check why the decodeURIComponent fails in the toString call, but for that i need to have your template and data to run it on my local.

**Comment by aleksandar78** [comment]
Hi, thanks for the reply. 
I've added recipe type 'html-with-browser-client' inside template body end everything works well. 

It was my fault. Probably more use-cases, with react or other js frameworks, on the web, would be very useful :-). 

Thanks

**Comment by bjrmatos** [comment]
> I've added recipe type 'html-with-browser-client' inside template body end everything works well.
> 
> It was my fault. Probably more use-cases, with react or other js frameworks, on the web, would be very useful :-).

it sounds like a good idea, we will have this in mind. thanks for the recommendation
